# source file : https://www.tiuweehan.com/blog/2020-09-10-docker-in-jenkins-in-docker/
# No need for Dockerfile

services:
  dind:
    image: docker:dind
    privileged: true
    container_name: dind
    expose:
      - 2375
    networks:
      - jenkins_dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-storage:/var/lib/docker

  jenkins:
    image: jenkins/jenkins:lts
    user: root  # Temporarily use root to install Docker CLI
    container_name: jenkins
    depends_on:
      - dind
    ports:
      - 7070:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: "tcp://dind:2375"
      JENKINS_OPTS: "--httpPort=8080"
    networks:
      - jenkins_dind
    command: |
      bash -c "
        curl -fsSL https://get.docker.com | sh
        usermod -aG docker jenkins
        su jenkins -c '/usr/local/bin/jenkins.sh'
      "

networks:
  jenkins_dind:
    driver: bridge

volumes:
  jenkins_home:
    name: jenkins_home
  dind-storage:
    name: dind-storage