# source file : https://www.tiuweehan.com/blog/2020-09-10-docker-in-jenkins-in-docker/
# No need for Dockerfile

version: '3.8'

services:
  dind:
    image: docker:dind
    privileged: true
    container_name: dind
    expose:
      - 2376
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - dind-storage:/var/lib/docker
    networks:
      - jenkins-network

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    depends_on:
      - dind
    ports:
      - 7070:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: tcp://dind:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    command: >
      bash -c "
        apt-get update && apt-get install -y docker-ce-cli
        groupadd -g 999 docker
        usermod -aG docker jenkins
        jenkins-plugin-cli --plugins docker-workflow blueocean
        /usr/local/bin/jenkins.sh
      "
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs
  dind-storage:
    name: dind-storage